export const companies = [
  "Moser Baer India Ltd.",
  "West Coast Paper Mills Ltd.",
  "HSIL Ltd.",
  "Thyrocare Technologies Ltd.",
  "EIH Ltd.",
  "Flex Engineering Ltd.[Merged]",
  "ICICI Prudential Life Insurance Company Ltd.",
  "QVC Realty Co. Ltd.",
  "Oswal Spinning & Weaving Mills Ltd.",
  "Bil Energy Systems Ltd.",
  "Jamna Auto Industries Ltd.",
  "K J International Ltd.",
  "Zen Technologies Ltd.",
  "Larsen & Toubro Infotech Ltd.",
  "Nalwa Sons Investments Ltd.",
  "SPEL Semiconductor Ltd.",
  "Vidhi Specialty Food Ingredients Ltd.",
  "Upper Ganges Sugar & Industries Ltd.",
  "Cosmo Films Ltd.",
  "Geekay Exim (India) Ltd.",
  "Diamond Power Infrastructure Ltd.",
  "Reliance Capital Ltd.",
  "Adani Transmission Ltd.",
  "Prestige Estates Projects Ltd.",
  "Xpro India Ltd."
]